DROP DATABASE MYPORTFOLIO
go

CREATE DATABASE MYPORTFOLIO
go

USE MYPORTFOLIO
go

CREATE TABLE GROUP_PRODUCT (
   ID_GROUP_PRODUCT     INT                  IDENTITY,
   DSC_GROUP_PRODUCT    NVARCHAR(40)         NOT NULL,
   CONSTRAINT PK_GROUP_PRODUCT PRIMARY KEY (ID_GROUP_PRODUCT)
)
go

CREATE INDEX GROUP_PRODUCT_I1 ON GROUP_PRODUCT (
DSC_GROUP_PRODUCT ASC
)
go

CREATE TABLE SUBGROUP_PRODUCT (
   ID_SUBGROUP_PRODUCT  INT                  IDENTITY,
   ID_GROUP_PRODUCT     INT                  NOT NULL,
   DSC_SUBGROUP_PRODUCT NVARCHAR(40)         NOT NULL,
   CONSTRAINT PK_SUBGROUP_PRODUCT PRIMARY KEY (ID_SUBGROUP_PRODUCT)
)
go

CREATE INDEX SUBGROUP_PRODUCT_I1 ON SUBGROUP_PRODUCT (
ID_GROUP_PRODUCT ASC
)
go

CREATE INDEX SUBGROUP_PRODUCT_I2 ON SUBGROUP_PRODUCT (
DSC_SUBGROUP_PRODUCT ASC
)
go

ALTER TABLE SUBGROUP_PRODUCT
   ADD CONSTRAINT SUBGROUP_PRD_FK_GROUP_PRD FOREIGN KEY (ID_GROUP_PRODUCT)
      REFERENCES GROUP_PRODUCT (ID_GROUP_PRODUCT)
go


use MYPORTFOLIO;
DELETE FROM SUBGROUP_PRODUCT;
DELETE FROM GROUP_PRODUCT;
select * from GROUP_PRODUCT order by 1;
select * from SUBGROUP_PRODUCT  order by 1;

insert into GROUP_PRODUCT
Values('TV');
insert into GROUP_PRODUCT
Values('Sofa');
insert into GROUP_PRODUCT
Values('Laptop');

insert into SUBGROUP_PRODUCT
values((SELECT ID_GROUP_PRODUCT 
		  FROM GROUP_PRODUCT 
		 WHERE DSC_GROUP_PRODUCT = 'TV'), '40"');
insert into SUBGROUP_PRODUCT
values((SELECT ID_GROUP_PRODUCT 
		  FROM GROUP_PRODUCT 
		 WHERE DSC_GROUP_PRODUCT = 'TV'), '43"');


insert into SUBGROUP_PRODUCT
values((SELECT ID_GROUP_PRODUCT 
		  FROM GROUP_PRODUCT 
		 WHERE DSC_GROUP_PRODUCT = 'Sofa'), 'For 3 people');
insert into SUBGROUP_PRODUCT
values((SELECT ID_GROUP_PRODUCT 
		  FROM GROUP_PRODUCT 
		 WHERE DSC_GROUP_PRODUCT = 'Sofa'), 'For 2 people');
insert into SUBGROUP_PRODUCT
values((SELECT ID_GROUP_PRODUCT 
		  FROM GROUP_PRODUCT 
		 WHERE DSC_GROUP_PRODUCT = 'Sofa'), 'For 4 people');

insert into SUBGROUP_PRODUCT
values((SELECT ID_GROUP_PRODUCT 
		  FROM GROUP_PRODUCT 
		 WHERE DSC_GROUP_PRODUCT = 'Laptop'), '13"');
insert into SUBGROUP_PRODUCT
values((SELECT ID_GROUP_PRODUCT 
		  FROM GROUP_PRODUCT 
		 WHERE DSC_GROUP_PRODUCT = 'Laptop'), '14"');
insert into SUBGROUP_PRODUCT
values((SELECT ID_GROUP_PRODUCT 
		  FROM GROUP_PRODUCT 
		 WHERE DSC_GROUP_PRODUCT = 'Laptop'), '15"');
insert into SUBGROUP_PRODUCT
values((SELECT ID_GROUP_PRODUCT 
		  FROM GROUP_PRODUCT 
		 WHERE DSC_GROUP_PRODUCT = 'Laptop'), '17"');

COMMIT;
